"""GIS-specific capability and dataset contract.

This module is the domain-owned catalog.  The generic Runtime consumes it
through ``DomainPack`` and does not need to know these dataset names.
"""

GIS_DATASET_TOOL_CAPABILITIES = {
    "admin_areas": ["get_dataset_schema", "range_query"],
    "dem": [
        "get_raster_metadata",
        "get_raster_statistics",
        "get_zonal_raster_statistics",
        "get_zonal_slope_statistics",
    ],
    "land_use": [
        "get_raster_metadata",
        "get_raster_statistics",
        "get_zonal_raster_statistics",
        "get_zonal_land_use_distribution",
    ],
    "roads": [
        "get_dataset_schema",
        "range_query",
        "get_zonal_vector_summary",
        "spatial_join",
    ],
    "water": [
        "get_dataset_schema",
        "range_query",
        "get_zonal_vector_summary",
        "spatial_join",
    ],
}

GIS_DATASET_GROUPS = {
    "core": ("admin_areas", "dem", "land_use"),
    "optional": ("roads", "water"),
}

GIS_CAPABILITIES = (
    {
        "id": "conversation",
        "label": "通用对话",
        "datasets": [],
        "tools": [],
        "result_types": ["direct_answer"],
        "environments": ["memory", "local", "production"],
        "geometry": "none",
    },
    {
        "id": "spatial_overview",
        "label": "区域空间总览",
        "datasets": ["admin_areas", "dem", "land_use", "roads", "water"],
        "tools": [
            "get_dataset_health_report", "get_dataset_schema", "range_query",
            "get_zonal_raster_statistics", "get_zonal_slope_statistics",
            "get_zonal_land_use_distribution", "get_zonal_vector_summary",
        ],
        "result_types": ["spatial_overview_result"],
        "environments": ["local", "production"],
        "geometry": "optional",
    },
    {
        "id": "spatial_analysis",
        "label": "组合式空间分析",
        "datasets": ["admin_areas", "dem", "land_use", "roads", "water"],
        "tools": [
            "get_dataset_health_report", "get_dataset_schema", "range_query",
            "get_zonal_raster_statistics", "get_zonal_slope_statistics",
            "get_zonal_land_use_distribution", "get_zonal_vector_summary",
            "get_zonal_buildability_analysis", "get_zonal_constrained_buildability_analysis",
        ],
        "result_types": ["spatial_analysis_result"],
        "environments": ["local", "production"],
        "geometry": "available_when_artifact_contains_features",
    },
    {
        "id": "admin_boundary_query",
        "label": "行政区边界查询",
        "datasets": ["admin_areas"],
        "tools": ["get_dataset_schema", "range_query"],
        "result_types": ["admin_area_result"],
        "environments": ["memory", "local", "production"],
        "geometry": "optional",
    },
    {
        "id": "raster_metadata",
        "label": "栅格元数据查询",
        "datasets": ["dem", "land_use"],
        "tools": ["get_raster_metadata"],
        "result_types": ["raster_metadata_result"],
        "environments": ["memory", "local", "production"],
        "geometry": "none",
    },
    {
        "id": "zonal_raster_statistics",
        "label": "区域栅格统计",
        "datasets": ["admin_areas", "dem", "land_use"],
        "tools": ["get_dataset_health_report", "get_zonal_raster_statistics"],
        "result_types": ["zonal_raster_statistics_result"],
        "environments": ["local", "production"],
        "geometry": "optional",
    },
    {
        "id": "zonal_terrain_land_use",
        "label": "区域地形与土地利用分析",
        "datasets": ["admin_areas", "dem", "land_use"],
        "tools": [
            "get_dataset_health_report", "get_dataset_schema", "range_query",
            "get_zonal_raster_statistics", "get_zonal_slope_statistics",
            "get_zonal_land_use_distribution",
        ],
        "result_types": ["terrain_land_use_analysis_result"],
        "environments": ["local", "production"],
        "geometry": "optional",
    },
    {
        "id": "buildability_screening",
        "label": "建设候选演示筛选",
        "datasets": ["admin_areas", "dem", "land_use"],
        "tools": ["get_dataset_health_report", "get_zonal_buildability_analysis"],
        "result_types": ["buildability_result", "buildability_comparison"],
        "environments": ["local", "production"],
        "geometry": "available_when_artifact_contains_features",
    },
    {
        "id": "constrained_buildability_screening",
        "label": "道路与水体约束筛选",
        "datasets": ["admin_areas", "dem", "land_use", "roads", "water"],
        "tools": [
            "get_dataset_health_report",
            "get_zonal_constrained_buildability_analysis",
        ],
        "result_types": ["constrained_buildability_result"],
        "environments": ["local", "production"],
        "geometry": "available_when_artifact_contains_features",
    },
    {
        "id": "vector_summary",
        "label": "道路与水体区域摘要",
        "datasets": ["admin_areas", "roads", "water"],
        "tools": ["get_dataset_health_report", "get_zonal_vector_summary"],
        "result_types": ["zonal_vector_summary_result"],
        "environments": ["local", "production"],
        "geometry": "optional",
    },
    {
        "id": "dataset_health",
        "label": "数据健康检查",
        "datasets": [],
        "tools": ["get_dataset_health_report"],
        "result_types": ["dataset_health_result"],
        "environments": ["memory", "local", "production"],
        "geometry": "none",
    },
    {
        "id": "raster_statistics",
        "label": "栅格值统计",
        "datasets": ["dem", "land_use"],
        "tools": ["get_raster_statistics"],
        "result_types": ["raster_statistics_result"],
        "environments": ["memory", "local", "production"],
        "geometry": "none",
    },
    {
        "id": "vector_query",
        "label": "矢量要素查询",
        "datasets": ["roads", "water"],
        "tools": ["get_dataset_schema", "range_query"],
        "result_types": ["vector_result"],
        "environments": ["memory", "local", "production"],
        "geometry": "optional",
    },
    {
        "id": "vector_relation",
        "label": "矢量空间关系查询",
        "datasets": ["roads", "water"],
        "tools": ["get_dataset_schema", "spatial_join"],
        "result_types": ["spatial_relation_result"],
        "environments": ["memory", "local", "production"],
        "geometry": "optional",
    },
    {
        "id": "legacy_road_slope",
        "label": "道路邻近高坡度查询（M0 兼容）",
        "datasets": ["roads", "slope"],
        "tools": ["get_dataset_schema", "range_query", "spatial_join"],
        "result_types": ["spatial_result"],
        "environments": ["memory", "local", "production"],
        "geometry": "optional",
    },
    {
        "id": "admin_raster_composite",
        "label": "行政区栅格复合统计",
        "datasets": ["admin_areas", "dem", "land_use"],
        "tools": [
            "get_dataset_health_report", "get_dataset_schema", "range_query",
            "get_zonal_raster_statistics",
        ],
        "result_types": ["zonal_raster_statistics_result"],
        "environments": ["local", "production"],
        "geometry": "optional",
    },
)
